name: libbpf-ci

on: 
  pull_request:
  push:
  schedule:
    - cron:  '0 18 * * *'

concurrency: 
  group: ci-test-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Kernel ${{ matrix.kernel }} on ${{ matrix.arch }} + selftests
    strategy:
      fail-fast: false
      matrix:
        include:
          - kernel: 'LATEST'
            runs_on: ubuntu-24.04
            arch: 'x86_64'
          #- kernel: '5.5.0'
          #  runs_on: ubuntu-24.04
          #  arch: 'x86_64'
          #- kernel: '4.9.0'
          #  runs_on: ubuntu-24.04
          #  arch: 'x86_64'
          #- kernel: 'LATEST'
          #  runs_on: ["s390x", "docker-noble-main"]
          #  arch: 's390x'
    uses: kernel-patches/vmtest/.github/workflows/kernel-build.yml@master
    with:
      arch: ${{ matrix.arch }}
      toolchain_full: gcc
      toolchain: gcc
      runs_on: ${{ toJSON(matrix.runs_on) }}
      llvm-version: 17
      kernel: ${{ inputs.kernel }}
      download_sources: true

